events { worker_connections 1024; }
http {
    upstream spring_app { server app:8080; }
    server {
        listen 80;
        client_max_body_size 10M;
        location / {
            proxy_pass http://spring_app;
            proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
            proxy_set_header X-Real-IP \;
        }
    }
}
